### PR TITLE
Change version number to 1.99 to avoid mime version conflicts

### PR DESCRIPTION
**Pull request by jbreynolds9**

### CODE REVIEW

**Comment by packrat386** [comment]
If we made breaking changes we need to tick a major version.

**Comment by jbreynolds9** [comment]
Ticking the major version is what broke it.

**Comment by packrat386** [comment]
We've made changes that break the gem's API since 1.14. We can't tick to 1.15 just to satisfy a version constraint because the gem now has a different API. See http://semver.org/

**Comment by jbreynolds9** [comment]
Then you need to un-break the API if you want NetCredit to continue to work
with Publicist.

**Comment by packrat386** [comment]
Netcredit should just pin to 1.14 if they're having issues with the new version.

**Pull request merged**
